version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./backups:/backups
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
    - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db